// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * U​n​a​u​t​h​o​r​i​z​e​d
	 */
	unauthorized: string
	/**
	 * A​c​c​e​s​s​ ​d​e​n​i​e​d
	 */
	access_denied: string
	/**
	 * P​l​e​a​s​e​ ​l​o​g​i​n​ ​i​n​ ​t​o​ ​g​e​t​ ​a​c​c​e​s​s
	 */
	login_to_access: string
	/**
	 * E​m​a​i​l​ ​w​a​s​ ​a​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d
	 */
	email_exist: string
	/**
	 * I​n​v​a​l​i​d​ ​e​m​a​i​l
	 */
	email_invalid: string
	/**
	 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​p​r​o​v​i​d​e​d
	 */
	email_or_username_required: string
	/**
	 * S​i​g​n​e​d​ ​u​p​ ​s​u​c​c​e​s​s​f​u​l​l​y​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​o​r​ ​v​e​r​i​f​i​c​a​t​i​o​n
	 */
	signup_success_check_email: string
	/**
	 * P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​o​r​ ​v​e​r​i​f​i​c​a​t​i​o​n
	 */
	check_email_to_verify: string
	/**
	 * L​o​g​g​e​d​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	login_success: string
	/**
	 * S​i​g​n​e​d​ ​u​p​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	signup_success: string
	/**
	 * I​n​v​a​l​i​d​ ​l​o​g​i​n​ ​c​r​e​d​e​n​t​i​a​l​s
	 */
	invalid_login_credentials: string
	/**
	 * A​c​c​o​u​n​t​ ​h​a​s​ ​b​e​e​n​ ​b​l​o​c​k​e​d
	 */
	you_are_banned: string
	/**
	 * A​c​c​o​u​n​t​ ​i​s​ ​b​l​o​c​k​e​d​ ​u​n​t​i​l​ 
	 */
	you_are_banned_until: string
	/**
	 * C​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	created_successfully: string
	/**
	 * A​d​d​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	added_successfully: string
	/**
	 * U​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	updated_successfully: string
	/**
	 * B​l​o​c​k​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	banned_successfully: string
	/**
	 * S​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	saved_successfully: string
	/**
	 * D​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	deleted_successfully: string
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n
	 */
	sth_went_wrong: string
	/**
	 * I​n​t​e​r​i​o​r​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	interior_created: string
	/**
	 * R​e​c​o​r​d​ ​w​i​t​h​ ​t​h​e​ ​s​a​m​e​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
	 */
	same_name_exists: string
	/**
	 * T​h​i​s​ ​m​o​d​e​l​ ​w​a​s​ ​a​l​r​e​a​d​y​ ​a​d​d​e​d​ ​t​o​ ​p​r​o​j​e​c​t
	 */
	model_in_project: string
	/**
	 * N​o​t​ ​f​o​u​n​d
	 */
	not_found: string
	/**
	 * U​s​e​r​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	user_404: string
	/**
	 * I​n​t​e​r​i​o​r​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	interior_404: string
	/**
	 * T​a​g​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	interior_model_404: string
	/**
	 * I​m​a​g​e​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	image_404: string
	/**
	 * F​i​l​e​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	file_404: string
	/**
	 * B​r​a​n​d​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	brand_404: string
	/**
	 * C​a​t​e​g​o​r​y​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	category_404: string
	/**
	 * M​o​d​e​l​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	model_404: string
	/**
	 * P​r​o​j​e​c​t​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	project_404: string
}

export type TranslationFunctions = {
	/**
	 * Unauthorized
	 */
	unauthorized: () => LocalizedString
	/**
	 * Access denied
	 */
	access_denied: () => LocalizedString
	/**
	 * Please login in to get access
	 */
	login_to_access: () => LocalizedString
	/**
	 * Email was already registered
	 */
	email_exist: () => LocalizedString
	/**
	 * Invalid email
	 */
	email_invalid: () => LocalizedString
	/**
	 * Email or username must be provided
	 */
	email_or_username_required: () => LocalizedString
	/**
	 * Signed up successfully. Please check your email for verification
	 */
	signup_success_check_email: () => LocalizedString
	/**
	 * Please check your email for verification
	 */
	check_email_to_verify: () => LocalizedString
	/**
	 * Logged in successfully
	 */
	login_success: () => LocalizedString
	/**
	 * Signed up successfully
	 */
	signup_success: () => LocalizedString
	/**
	 * Invalid login credentials
	 */
	invalid_login_credentials: () => LocalizedString
	/**
	 * Account has been blocked
	 */
	you_are_banned: () => LocalizedString
	/**
	 * Account is blocked until 
	 */
	you_are_banned_until: () => LocalizedString
	/**
	 * Created successfully
	 */
	created_successfully: () => LocalizedString
	/**
	 * Added successfully
	 */
	added_successfully: () => LocalizedString
	/**
	 * Updated successfully
	 */
	updated_successfully: () => LocalizedString
	/**
	 * Blocked successfully
	 */
	banned_successfully: () => LocalizedString
	/**
	 * Saved successfully
	 */
	saved_successfully: () => LocalizedString
	/**
	 * Deleted successfully
	 */
	deleted_successfully: () => LocalizedString
	/**
	 * Something went wrong. Please, try again
	 */
	sth_went_wrong: () => LocalizedString
	/**
	 * Interior created successfully
	 */
	interior_created: () => LocalizedString
	/**
	 * Record with the same name already exists
	 */
	same_name_exists: () => LocalizedString
	/**
	 * This model was already added to project
	 */
	model_in_project: () => LocalizedString
	/**
	 * Not found
	 */
	not_found: () => LocalizedString
	/**
	 * User was not found
	 */
	user_404: () => LocalizedString
	/**
	 * Interior was not found
	 */
	interior_404: () => LocalizedString
	/**
	 * Tag was not found
	 */
	interior_model_404: () => LocalizedString
	/**
	 * Image was not found
	 */
	image_404: () => LocalizedString
	/**
	 * File was not found
	 */
	file_404: () => LocalizedString
	/**
	 * Brand was not found
	 */
	brand_404: () => LocalizedString
	/**
	 * Category was not found
	 */
	category_404: () => LocalizedString
	/**
	 * Model was not found
	 */
	model_404: () => LocalizedString
	/**
	 * Project was not found
	 */
	project_404: () => LocalizedString
}

export type Formatters = {}
