// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ru'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * U​n​a​u​t​h​o​r​i​z​e​d
	 */
	unauthorized: string
	/**
	 * P​l​e​a​s​e​ ​l​o​g​i​n​ ​i​n​ ​t​o​ ​g​e​t​ ​a​c​c​e​s​s
	 */
	login_to_access: string
	/**
	 * U​s​e​r​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	user_404: string
	/**
	 * E​m​a​i​l​ ​w​a​s​ ​a​l​r​e​a​d​y​ ​r​e​g​i​s​t​e​r​e​d
	 */
	email_exist: string
	/**
	 * I​n​v​a​l​i​d​ ​e​m​a​i​l
	 */
	email_invalid: string
	/**
	 * E​m​a​i​l​ ​o​r​ ​u​s​e​r​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​p​r​o​v​i​d​e​d
	 */
	email_or_username_required: string
	/**
	 * S​i​g​n​e​d​ ​u​p​ ​s​u​c​c​e​s​s​f​u​l​l​y​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​o​r​ ​v​e​r​i​f​i​c​a​t​i​o​n
	 */
	signup_success_check_email: string
	/**
	 * P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l​ ​f​o​r​ ​v​e​r​i​f​i​c​a​t​i​o​n
	 */
	check_email_to_verify: string
	/**
	 * L​o​g​g​e​d​ ​i​n​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	login_success: string
	/**
	 * S​i​g​n​e​d​ ​u​p​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	signup_success: string
	/**
	 * I​n​v​a​l​i​d​ ​l​o​g​i​n​ ​c​r​e​d​e​n​t​i​a​l​s
	 */
	invalid_login_credentials: string
	/**
	 * S​a​v​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	saved_successfully: string
	/**
	 * D​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	deleted_successfully: string
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.​ ​P​l​e​a​s​e​,​ ​t​r​y​ ​a​g​a​i​n
	 */
	sth_went_wrong: string
	/**
	 * I​n​t​e​r​i​o​r​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	interior_404: string
	/**
	 * I​n​t​e​r​i​o​r​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
	 */
	interior_created: string
	/**
	 * I​m​a​g​e​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d
	 */
	image_404: string
}

export type TranslationFunctions = {
	/**
	 * Unauthorized
	 */
	unauthorized: () => LocalizedString
	/**
	 * Please login in to get access
	 */
	login_to_access: () => LocalizedString
	/**
	 * User was not found
	 */
	user_404: () => LocalizedString
	/**
	 * Email was already registered
	 */
	email_exist: () => LocalizedString
	/**
	 * Invalid email
	 */
	email_invalid: () => LocalizedString
	/**
	 * Email or username must be provided
	 */
	email_or_username_required: () => LocalizedString
	/**
	 * Signed up successfully. Please check your email for verification
	 */
	signup_success_check_email: () => LocalizedString
	/**
	 * Please check your email for verification
	 */
	check_email_to_verify: () => LocalizedString
	/**
	 * Logged in successfully
	 */
	login_success: () => LocalizedString
	/**
	 * Signed up successfully
	 */
	signup_success: () => LocalizedString
	/**
	 * Invalid login credentials
	 */
	invalid_login_credentials: () => LocalizedString
	/**
	 * Saved successfully
	 */
	saved_successfully: () => LocalizedString
	/**
	 * Deleted successfully
	 */
	deleted_successfully: () => LocalizedString
	/**
	 * Something went wrong. Please, try again
	 */
	sth_went_wrong: () => LocalizedString
	/**
	 * Interior was not found
	 */
	interior_404: () => LocalizedString
	/**
	 * Interior created successfully
	 */
	interior_created: () => LocalizedString
	/**
	 * Image was not found
	 */
	image_404: () => LocalizedString
}

export type Formatters = {}
